name: Radar diário

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        working-directory: tanacara
        run: npm install

      - name: Generate posts
        working-directory: tanacara
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_KEY }}
        run: npm run gen:radar

      - name: Commit and push
        run: |
          git config user.name "tanacara-bot"
          git config user.email "actions@users.noreply.github.com"
          git add tanacara/content/radar
          git commit -m "chore(radar): update" || echo "Nothing to commit"
          git push
